### ISSUE TITLE
The library fails to compile on Linux

### ISSUE THREAD

**Issue by duhanebel** [zacsketches/Arduino_Vector#2]
Vector.h includes “arduino.h” instead of the correct “Arduino.h”. This fails on case-sensitive OSs like *NIX

**Comment by micooke** [comment]
+1

**Comment by jngermon** [comment]
+1
The PR of @duhanebel is ready and works for me.

**Comment by zacsketches** [comment]
@duhanebel thanks for this little fix, and also to @micooke and @jngermon for validating the fix.
